[project]
name = "gdv"
version = "0.1.0"
description = "Python package for CSE620 Project 1"
readme = "README.md"
authors = [
    { name = "Kenneth O'Dell", email = "kenneth.l.odell@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "polars>=1.44.1",
    "scipy>=1.17.1",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
